apiVersion: apps/v1
kind: Deployment
metadata:
  name: causas-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: causas-web
        image: alejandrogh/causas-web
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: causas-web-service
  labels:
    app: app
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 3000
    name: http
    nodePort: 30080
  selector:
    app: app
